on: [pull_request]

jobs:
  analyse_code_job:
    runs-on: ubuntu-latest
    name: A job to analyse the code with Get the Green client
    steps:
    - name: Analyse the code step
      uses: codeobservability/client-action@master
      with:
        co-repo-key: ${{ secrets.CO_REPO_KEY }}
