on: [pull_request]

jobs:
  analyse_code_job:
    runs-on: ubuntu-latest
    name: Analyse the code with Code Observability
    steps:
    - uses: actions/checkout@v3
    - name: Analyse the code step
      uses: codeobservability/client-action@master
      with:
        co-repo-key: ${{ secrets.CO_REPO_KEY }}
